//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeInv.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeInv.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev seçimi olmadan kategori kaydedilemez!.
        /// </summary>
        public static string Category_HomeIsMandatory {
            get {
                return ResourceManager.GetString("Category_HomeIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üçüncü seviyede kategori eklenemez..
        /// </summary>
        public static string Category_MaxThreeLevelsAllowed {
            get {
                return ResourceManager.GetString("Category_MaxThreeLevelsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı isimde başka bir kategori mevcut.
        /// </summary>
        public static string Category_SameNameExists {
            get {
                return ResourceManager.GetString("Category_SameNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondalıklı sayılar virgülle ayrılmalıdır..
        /// </summary>
        public static string Error_DecimalsShouldBeSeparatedByComma {
            get {
                return ResourceManager.GetString("Error_DecimalsShouldBeSeparatedByComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum uçmus, giriş yapıp tekrar bir deneyin. Giriş sağ üstte bir yerlerde..
        /// </summary>
        public static string Error_LoggedOut {
            get {
                return ResourceManager.GetString("Error_LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string Generic_Amount {
            get {
                return ResourceManager.GetString("Generic_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye Dön.
        /// </summary>
        public static string Generic_BackToList {
            get {
                return ResourceManager.GetString("Generic_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Generic_Description {
            get {
                return ResourceManager.GetString("Generic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Generic_Name {
            get {
                return ResourceManager.GetString("Generic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyut Tipi.
        /// </summary>
        public static string Generic_Size {
            get {
                return ResourceManager.GetString("Generic_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı isimde başka bir eviniz var, lütfen farklı bir isim giriniz..
        /// </summary>
        public static string Home_Error_SameNameExists {
            get {
                return ResourceManager.GetString("Home_Error_SameNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev seçimi zorunludur..
        /// </summary>
        public static string HomeSelectionIsMandatory {
            get {
                return ResourceManager.GetString("HomeSelectionIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu evde, bu isimde bir nesne zaten var!.
        /// </summary>
        public static string ItemNameExists {
            get {
                return ResourceManager.GetString("ItemNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoğun odası seçilmeden stoğun nerede olduğunu bilemeyiz ki ama....
        /// </summary>
        public static string ItemStock_Error_AreaIdEmpty {
            get {
                return ResourceManager.GetString("ItemStock_Error_AreaIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İtem Tanımı seçimi yapılmadan stok güncellenemez ki ama....
        /// </summary>
        public static string ItemStock_Error_ItemDefinitionIdEmpty {
            get {
                return ResourceManager.GetString("ItemStock_Error_ItemDefinitionIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu aksiyon sadece stokta bulunan bir üründe güncelleme yapılırken seçilebilir!.
        /// </summary>
        public static string ItemStock_Error_ItemStockIdEmptyOnUpdateAction {
            get {
                return ResourceManager.GetString("ItemStock_Error_ItemStockIdEmptyOnUpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaç kilo, kaç tane, kaç ney bu ürün :(.
        /// </summary>
        public static string ItemStock_Error_SizeEmpty {
            get {
                return ResourceManager.GetString("ItemStock_Error_SizeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoktaki ürünün boyunu posunu da bilmeyelim mi?....
        /// </summary>
        public static string ItemStock_Error_SizeUnitIdEmpty {
            get {
                return ResourceManager.GetString("ItemStock_Error_SizeUnitIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareketin Yapıldığı Tarih.
        /// </summary>
        public static string ItemStockEntry_ActionDate {
            get {
                return ResourceManager.GetString("ItemStockEntry_ActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market, Kişi falan....
        /// </summary>
        public static string ItemStockEntry_ActionTarget {
            get {
                return ResourceManager.GetString("ItemStockEntry_ActionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda.
        /// </summary>
        public static string ItemStockEntry_AreaId {
            get {
                return ResourceManager.GetString("ItemStockEntry_AreaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoğa Giren Miktar.
        /// </summary>
        public static string ItemStockEntry_EntryAmount {
            get {
                return ResourceManager.GetString("ItemStockEntry_EntryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Kullanma Tarihi.
        /// </summary>
        public static string ItemStockEntry_ExpirationDate {
            get {
                return ResourceManager.GetString("ItemStockEntry_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string ItemStockEntry_ItemDefinitionId {
            get {
                return ResourceManager.GetString("ItemStockEntry_ItemDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyut Birimi.
        /// </summary>
        public static string ItemStockEntry_SizeUnitId {
            get {
                return ResourceManager.GetString("ItemStockEntry_SizeUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Giriş Tipi.
        /// </summary>
        public static string ItemStockEntry_StockActionTypeId {
            get {
                return ResourceManager.GetString("ItemStockEntry_StockActionTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string ItemStockEntry_TotalPrice {
            get {
                return ResourceManager.GetString("ItemStockEntry_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori oluşturuldu..
        /// </summary>
        public static string Success_Category_Create {
            get {
                return ResourceManager.GetString("Success_Category_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla gerçekleşti..
        /// </summary>
        public static string Success_Generic {
            get {
                return ResourceManager.GetString("Success_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni ev oluşturuldu..
        /// </summary>
        public static string Success_Home_Create {
            get {
                return ResourceManager.GetString("Success_Home_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev başarıyla güncellendi..
        /// </summary>
        public static string Success_Home_Edit {
            get {
                return ResourceManager.GetString("Success_Home_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı zaten bu evde bulunuyor!.
        /// </summary>
        public static string UserIsAlreadyInThatHome {
            get {
                return ResourceManager.GetString("UserIsAlreadyInThatHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamayı kullanmaya başlamadan önce ilk evinizi oluşturmanız veya bir eve davet edilmeniz gerekiyor..
        /// </summary>
        public static string Warning_HomeNeededToUseTheApp {
            get {
                return ResourceManager.GetString("Warning_HomeNeededToUseTheApp", resourceCulture);
            }
        }
    }
}
